version: "3"

services:
  frontend: # 이름은 어떤걸로 지정해도 상관없음
    build:
      context: ./frontend # 도커파일 위치 명시
    volumes:
      - /app/node_modules #도커 /app/node_modules는 맵핑을 따로 안해주겠다.
      - /home/ubuntu/cert:/home/ubuntu/cert #https연결을 위한
    ports:
      - "3000:3000" # EC2 포트 : 컨테이너 포트
      - "80:80"
      - "443:443"
