spring:
  kafka:
    consumer:
      bootstrap-servers: k6s102.p.ssafy.io:8092
      group-id: test-log
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: k6s102.p.ssafy.io:8092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://beSpringBoot:s102threaddump@k6s102.p.ssafy.io:27017/threaddump?authSource=threaddump&tls=true

