version: "3"
services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ../cert:/etc/certs:ro
        restart: always
